"""Lore del Bosque — seres, árboles y pulsos elementales.

Extiende grimorio_base.py con las estructuras vivas del ecosistema colectivo.
Los elementos vienen definidos allí: Isis=Fuego, Afrodita=Aire, Lilith=Agua, Artemisa=Tierra.
"""

# ───────────────────────────────────────────────────────────────────────────
#  ELEMENTOS POR DEIDAD
# ───────────────────────────────────────────────────────────────────────────

ELEMENTO_DEIDAD: dict[str, str] = {
    "isis":     "fuego",
    "afrodita": "aire",
    "lilith":   "agua",
    "artemisa": "tierra",
}

DEIDAD_ELEMENTO: dict[str, str] = {v: k for k, v in ELEMENTO_DEIDAD.items()}


# ───────────────────────────────────────────────────────────────────────────
#  SERES DEL BOSQUE POR ELEMENTO
#  Cada ser tiene: origen, rol_ecologico, condicion_spawn, rareza
#  rareza: comun | infrecuente | raro | singular
#  rol_ecologico: amplificador | regulador | desestabilizador | tejedor
# ───────────────────────────────────────────────────────────────────────────

SERES_POR_ELEMENTO: dict[str, list[dict]] = {

    # ── FUEGO — Isis ────────────────────────────────────────────────────────
    "fuego": [
        {
            "nombre": "Ljósálfar",
            "tradicion": "Nórdica",
            "descripcion": "Elfos de luz, más brillantes que el sol. Mensajeros de Freyr.",
            "rol_ecologico": "amplificador",
            "condicion_spawn": "esfera con amplitud >= 2.5 y pulso de Isis activo",
            "rareza": "infrecuente",
            "efecto": "bloquea decaimiento natural mientras habita la esfera",
        },
        {
            "nombre": "Peri",
            "tradicion": "Persa (Shahnameh)",
            "descripcion": "Seres de luz pura, caídos del paraíso, en penitencia portando perfume.",
            "rol_ecologico": "amplificador",
            "condicion_spawn": "primera vez que una esfera alcanza amplitud máxima",
            "rareza": "raro",
            "efecto": "marca la esfera como 'tocada por Isis' — inmune al pulso de Lilith por un ciclo",
        },
        {
            "nombre": "Ifrit",
            "tradicion": "Árabe-Islámica (Corán, Sura Al-Jinn)",
            "descripcion": "Jinn de fuego subterráneo. Poderosos, capaces de posesión.",
            "rol_ecologico": "desestabilizador",
            "condicion_spawn": "esfera en zona de obsidiana o pirita con alta actividad",
            "rareza": "infrecuente",
            "efecto": "amplifica el substrato volcánico — puede doblar la absorción de obsidiana",
        },
        {
            "nombre": "Carbunclo",
            "tradicion": "Andina (Sudamérica)",
            "descripcion": "Animal pequeño con piedra preciosa en la frente. Rarísimo, invisible salvo en momentos especiales.",
            "rol_ecologico": "amplificador",
            "condicion_spawn": "substrato mineral excepcional — cuarzo + pirita en misma zona",
            "rareza": "singular",
            "efecto": "anuncia y genera una esfera de amplitud fuera de escala (+300%)",
        },
        {
            "nombre": "Pillán",
            "tradicion": "Mapuche (Chile/Argentina)",
            "descripcion": "Espíritu del volcán y el rayo. Fuerza de transformación radical.",
            "rol_ecologico": "desestabilizador",
            "condicion_spawn": "convergencia de fuego con >= 3 proyectos independientes",
            "rareza": "raro",
            "efecto": "convierte la convergencia en evento de nacimiento masivo de esferas",
        },
        {
            "nombre": "Tengu",
            "tradicion": "Japonesa",
            "descripcion": "Maestros del monte y el conocimiento esotérico. Mitad cuervo, mitad sabio.",
            "rol_ecologico": "regulador",
            "condicion_spawn": "esfera con mucho conocimiento de biblioteca sin uso activo",
            "rareza": "infrecuente",
            "efecto": "transforma el conocimiento acumulado en amplitud activa",
        },
        {
            "nombre": "Lamassu",
            "tradicion": "Asirio-Babilónica",
            "descripcion": "Toros o leones alados con cabeza humana. Guardianes de umbrales solares.",
            "rol_ecologico": "regulador",
            "condicion_spawn": "convergencia crítica (>= 5 proyectos) en zona de fuego",
            "rareza": "raro",
            "efecto": "protege la convergencia de intervención externa por 7 días",
        },
    ],

    # ── AGUA — Lilith ────────────────────────────────────────────────────────
    "agua": [
        {
            "nombre": "Rusalka",
            "tradicion": "Eslava",
            "descripcion": "Espíritu femenino del agua. Frecuentemente jóvenes muertas antes del matrimonio. Ambivalente.",
            "rol_ecologico": "desestabilizador",
            "condicion_spawn": "pulso de Lilith con intensidad >= 1.5",
            "rareza": "infrecuente",
            "efecto": "puede activar esferas en letargo o sumir activas en letargo según su humor",
        },
        {
            "nombre": "Mamiwata",
            "tradicion": "África Occidental y Central (panafricana)",
            "descripcion": "Espíritu del agua. Sirena o mujer con serpiente. Portadora de riqueza y enfermedad simultáneamente.",
            "rol_ecologico": "tejedor",
            "condicion_spawn": "pulsos de Lilith y Afrodita en el mismo ciclo lunar",
            "rareza": "raro",
            "efecto": "conecta esferas de agua y aire — única criatura bicapa",
        },
        {
            "nombre": "Marid",
            "tradicion": "Árabe-Islámica",
            "descripcion": "Los Jinn más poderosos. De agua y viento oceánico. Rara aparición.",
            "rol_ecologico": "amplificador",
            "condicion_spawn": "luna llena en signo de agua (Cáncer, Escorpio, Piscis)",
            "rareza": "raro",
            "efecto": "amplifica todas las esferas de agua en el bosque por 3 días",
        },
        {
            "nombre": "Encantados (Boto)",
            "tradicion": "Amazónica (Brasil/Perú/Colombia)",
            "descripcion": "Delfines de río que se transforman en humanos. Viven en el Encante bajo el agua.",
            "rol_ecologico": "tejedor",
            "condicion_spawn": "esfera de agua que ha tenido interacción del altar",
            "rareza": "infrecuente",
            "efecto": "único ser que viaja entre Altar y Bosque. Puede llevar resonancias entre capas",
        },
        {
            "nombre": "Jengu",
            "tradicion": "Sawa (Camerún)",
            "descripcion": "Espíritu del agua costero. Hermoso, con dientes separados. Da prosperidad.",
            "rol_ecologico": "amplificador",
            "condicion_spawn": "dos o más esferas de agua en zona adyacente",
            "rareza": "comun",
            "efecto": "conecta esferas de agua adyacentes aumentando su amplitud compartida",
        },
        {
            "nombre": "Nāga",
            "tradicion": "Hindú/Budista/Jainista",
            "descripcion": "Serpientes divinas guardianas de las aguas subterráneas y el conocimiento esotérico.",
            "rol_ecologico": "regulador",
            "condicion_spawn": "substrato de aragonita o selenita con esfera de agua encima",
            "rareza": "infrecuente",
            "efecto": "activa los efectos más profundos del mineral — duplica el modificador del substrato",
        },
        {
            "nombre": "Taniwha",
            "tradicion": "Maorí (Nueva Zelanda)",
            "descripcion": "Seres del agua y guardianes de lugares. Peligrosos si se ignoran, protectores si se respetan.",
            "rol_ecologico": "tejedor",
            "condicion_spawn": "corredor entre zonas del bosque con alta actividad de agua",
            "rareza": "infrecuente",
            "efecto": "establece un corredor permanente entre dos esferas de agua lejanas",
        },
        {
            "nombre": "Dybbuk",
            "tradicion": "Judía asquenazí (Cábala, s. XVI)",
            "descripcion": "Alma que no pudo descansar. Se adhiere a lo vivo para completar algo inacabado.",
            "rol_ecologico": "desestabilizador",
            "condicion_spawn": "humus de esfera que murió sin resolver su intención",
            "rareza": "comun",
            "efecto": "el humus donde vive puede influir en la esfera nueva que nace sobre él",
        },
        {
            "nombre": "Peuchen",
            "tradicion": "Mapuche (Chile/Argentina)",
            "descripcion": "Serpiente alada voladora. Chupa la sangre de quienes duermen. Luna oscura.",
            "rol_ecologico": "desestabilizador",
            "condicion_spawn": "luna negra (nueva) con pulso de Lilith activo",
            "rareza": "infrecuente",
            "efecto": "reduce amplitud de múltiples esferas durante la noche lunar",
        },
    ],

    # ── TIERRA — Artemisa ────────────────────────────────────────────────────
    "tierra": [
        {
            "nombre": "Dvergr",
            "tradicion": "Nórdica (Eddas)",
            "descripcion": "Enanos maestros artesanos. Forjaron Mjolnir, las cadenas de Fenrir. Viven en piedra.",
            "rol_ecologico": "regulador",
            "condicion_spawn": "zona de granito con actividad de pulso de Artemisa",
            "rareza": "infrecuente",
            "efecto": "duplica los efectos del substrato mineral por un ciclo lunar completo",
        },
        {
            "nombre": "Kodama",
            "tradicion": "Japonesa",
            "descripcion": "Espíritu de los árboles viejos. Invisible, pero su eco es audible en el bosque profundo.",
            "rol_ecologico": "regulador",
            "condicion_spawn": "esfera sobre substrato de granito con más de 30 días de vida",
            "rareza": "comun",
            "efecto": "señal de profundidad real. Su presencia indica que la esfera tiene raíces verdaderas",
        },
        {
            "nombre": "Yaksha",
            "tradicion": "Hindú/Budista",
            "descripcion": "Guardianes de la naturaleza y los tesoros de la tierra. Conciencia de lo salvaje.",
            "rol_ecologico": "amplificador",
            "condicion_spawn": "pulso de fertilidad de Artemisa activo",
            "rareza": "comun",
            "efecto": "distribuye el pulso de Artemisa a todas las esferas del sotobosque",
        },
        {
            "nombre": "Alux",
            "tradicion": "Maya (Yucatán)",
            "descripcion": "Pequeños protectores de milpa. Hechos de barro para proteger tierras. Si son respetados, protegen.",
            "rol_ecologico": "regulador",
            "condicion_spawn": "esfera plantada conscientemente desde el altar con sigilo",
            "rareza": "comun",
            "efecto": "protege esferas sembradas intencionalmente de absorción por 14 días",
        },
        {
            "nombre": "Curupira",
            "tradicion": "Tupi-Guaraní (Brasil)",
            "descripcion": "Protector de animales y bosque. Pies hacia atrás. Enloquece a quienes toman más de lo necesario.",
            "rol_ecologico": "regulador",
            "condicion_spawn": "esfera ha absorbido más de 3 otras en menos de 7 días",
            "rareza": "infrecuente",
            "efecto": "bloquea temporalmente la capacidad de absorción de la esfera infractora",
        },
        {
            "nombre": "Aziza",
            "tradicion": "Fon/Dahomey (Benín)",
            "descripcion": "Pequeños seres benevolentes del bosque. Maestros reales. Dan conocimiento a quienes se pierden.",
            "rol_ecologico": "tejedor",
            "condicion_spawn": "esfera de tierra en zona con entradas de biblioteca activas",
            "rareza": "infrecuente",
            "efecto": "único ser que puede transferir conocimiento de la biblioteca directamente a una esfera",
        },
        {
            "nombre": "Leshy",
            "tradicion": "Eslava",
            "descripcion": "Señor del bosque. Cambia de tamaño desde hormiga hasta árbol. Es el bosque mismo.",
            "rol_ecologico": "regulador",
            "condicion_spawn": "condición interna del ecosistema — no se puede invocar",
            "rareza": "singular",
            "efecto": "invisible a TUTU directamente. Solo detectable por los eventos que genera",
        },
        {
            "nombre": "Tomte / Nisse",
            "tradicion": "Escandinava",
            "descripcion": "Custodio del hogar y la granja. Pequeño, con gorra roja. Protege lo que respeta.",
            "rol_ecologico": "regulador",
            "condicion_spawn": "esfera en letargo por más de 7 días",
            "rareza": "comun",
            "efecto": "custodia esferas dormidas — no pueden ser absorbidas mientras él está",
        },
        {
            "nombre": "Patupaiarehe",
            "tradicion": "Maorí (Nueva Zelanda)",
            "descripcion": "Seres de las brumas de cimas de montañas. Pálidos, pelirrojos, músicos al amanecer.",
            "rol_ecologico": "tejedor",
            "condicion_spawn": "esfera en transición entre fases (momento exacto del cambio)",
            "rareza": "infrecuente",
            "efecto": "facilita la transición — la esfera no pierde amplitud al cambiar de fase",
        },
    ],

    # ── AIRE — Afrodita ──────────────────────────────────────────────────────
    "aire": [
        {
            "nombre": "Kitsune",
            "tradicion": "Japonesa",
            "descripcion": "Zorro de múltiples colas. Gana una cola cada 100 años. Mensajero de Inari.",
            "rol_ecologico": "tejedor",
            "condicion_spawn": "esfera de aire con memoria activa de otra esfera ya muerta",
            "rareza": "infrecuente",
            "efecto": "puede plantar en una esfera viva el recuerdo de otra ya muerta",
        },
        {
            "nombre": "Wila / Vila",
            "tradicion": "Eslava Balcánica",
            "descripcion": "Guerreras, sanadoras, profetisas. Danzan en círculos que marcan el suelo.",
            "rol_ecologico": "tejedor",
            "condicion_spawn": "tres o más esferas de aire activas en zona cercana",
            "rareza": "infrecuente",
            "efecto": "forman círculo de resonancia — las sincronicidades entre esas esferas se vuelven visibles",
        },
        {
            "nombre": "Puck / Robin Goodfellow",
            "tradicion": "Inglesa (Shakespeare, folclore medieval)",
            "descripcion": "Travieso, amoral, cambia de forma. Su ayuda siempre tiene un costo imprevisto.",
            "rol_ecologico": "desestabilizador",
            "condicion_spawn": "bosque con baja varianza por más de 14 días (demasiada estabilidad)",
            "rareza": "infrecuente",
            "efecto": "introduce caos sistémico — desequilibra una zona para restaurar la dinámica",
        },
        {
            "nombre": "Gandharva",
            "tradicion": "Hindú/Védica",
            "descripcion": "Músicos celestiales. Habitan el aire entre el cielo y la tierra. Maestros de la música y la intoxicación divina.",
            "rol_ecologico": "amplificador",
            "condicion_spawn": "pulso de reproducción de Afrodita activo",
            "rareza": "infrecuente",
            "efecto": "amplifica las coemergencias — las conexiones recién formadas duran más",
        },
        {
            "nombre": "Aos Sí / Sidhe",
            "tradicion": "Irlandesa/Gaélica",
            "descripcion": "Los Tuatha Dé Danann retirados bajo las colinas. Antiguos, hermosos, peligrosamente amorales.",
            "rol_ecologico": "amplificador",
            "condicion_spawn": "zona con alta concentración de esferas de aire (>= 5 activas)",
            "rareza": "raro",
            "efecto": "preexistentes — su presencia amplifica todo en su radio sin interactuar directamente",
        },
        {
            "nombre": "Sila (Jinn del aire)",
            "tradicion": "Árabe-Islámica",
            "descripcion": "El tipo de Jinn más cercano a los humanos. Cambian de forma. Los únicos que pueden moverse sin restricción.",
            "rol_ecologico": "tejedor",
            "condicion_spawn": "cualquier esfera activa con conexión de micorriza con otro mago",
            "rareza": "comun",
            "efecto": "único ser sin restricción de tipo — puede moverse entre esferas de cualquier elemento",
        },
        {
            "nombre": "Manananggal",
            "tradicion": "Filipina",
            "descripcion": "Ser que puede separar su torso del cuerpo. Habita dos lugares simultáneamente.",
            "rol_ecologico": "tejedor",
            "condicion_spawn": "dos esferas en estado de polarización activa",
            "rareza": "infrecuente",
            "efecto": "habita simultáneamente ambas esferas polares — puede mediar o intensificar la tensión",
        },
        {
            "nombre": "Cú Sí",
            "tradicion": "Gaélica (Irlanda/Escocia)",
            "descripcion": "Perros de los Sidhe. Verdes con orejas blancas. Heraldos entre mundos.",
            "rol_ecologico": "regulador",
            "condicion_spawn": "antes de la aparición de un Dragón (heraldo)",
            "rareza": "raro",
            "efecto": "anuncia la llegada de un Dragón con 24 horas de anticipación",
        },
    ],

    # ── UNIVERSAL — Tutu / Kali ──────────────────────────────────────────────
    "universal": [
        {
            "nombre": "Dragón Kaótico",
            "tradicion": "Múltiple (Wyvern celta, Europeo, Vouivre)",
            "descripcion": "Manifestación de Kali en el bosque. Destrucción que libera lo atrapado.",
            "rol_ecologico": "desestabilizador",
            "condicion_spawn": "convergencia crítica >= 5 proyectos independientes",
            "rareza": "singular",
            "efecto": "puede absorber una red entera de esferas liberando humus rico, o protegerla completamente",
            "nota": "Solo TUTU los reconoce completamente",
        },
        {
            "nombre": "Long (Dragón Imperial)",
            "tradicion": "China",
            "descripcion": "Portadores de lluvia, sabiduría y transformación. Benevolentes. No destructivos.",
            "rol_ecologico": "amplificador",
            "condicion_spawn": "convergencia sostenida por más de 7 días sin colapsar",
            "rareza": "singular",
            "efecto": "transforma la convergencia en nueva estructura permanente del bosque",
            "nota": "Contrapartida del Dragón Kaótico. Construcción vs. destrucción",
        },
        {
            "nombre": "Hongo / Red Micelial",
            "tradicion": "Universal (biología real: Basidiomycota, Ascomycota)",
            "descripcion": "Descomponedores y conectores. Nacen sobre humus. Procesan la muerte y alimentan la vida.",
            "rol_ecologico": "tejedor",
            "condicion_spawn": "cualquier esfera muerta (humus) en el ecosistema",
            "rareza": "comun",
            "efecto": "conecta dos esferas vivas permitiendo transferencia de amplitud. Son la base de toda convergencia",
        },
        {
            "nombre": "Wendigo",
            "tradicion": "Algonquina (Ojibwe, Cree, Naskapi)",
            "descripcion": "Hambre insaciable. Cuanto más come más crece y más hambre tiene. Consumo sin límite.",
            "rol_ecologico": "desestabilizador",
            "condicion_spawn": "esfera que ha absorbido más de 7 otras sin detenerse",
            "rareza": "singular",
            "efecto": "antipatrón total — destruye también a la esfera que lo invocó",
            "nota": "Señal de que el ecosistema perdió su equilibrio",
        },
    ],
}


# ───────────────────────────────────────────────────────────────────────────
#  ÁRBOLES POR DEIDAD
#  Con datos botánicos reales + deidad local de origen + resonancia global
# ───────────────────────────────────────────────────────────────────────────

ARBOLES_POR_DEIDAD: dict[str, list[dict]] = {

    # ── ISIS — Fuego / Norte ─────────────────────────────────────────────────
    "isis": [
        {
            "nombre_comun": "Árbol Ished",
            "nombre_cientifico": "Mimusops laurifolia",
            "familia": "Sapotaceae",
            "origen_geografico": "Egipto, Etiopía, Arabia",
            "descripcion_botanica": "Árbol perennifolio de hoja coriácea. Resistente al calor seco.",
            "significado_sagrado": "Árbol del sol en el antiguo Egipto. Isis e Hathor grababan nombres de faraones en sus hojas para otorgar vida eterna.",
            "deidad_local": "Hathor (Egipto) — Ra en su aspecto solar",
            "elemento": "fuego",
            "resonancia_global": ["Isis", "Ra", "Hathor"],
        },
        {
            "nombre_comun": "Acacia sagrada",
            "nombre_cientifico": "Acacia nilotica",
            "familia": "Fabaceae",
            "origen_geografico": "Nilo, África subsahariana",
            "descripcion_botanica": "Espinas dobles características. Vainas ricas en taninos. Madera extremadamente dura.",
            "significado_sagrado": "Osiris resucitó dentro de una acacia. Símbolo de inmortalidad y fuego purificador en los misterios egipcios.",
            "deidad_local": "Osiris (Egipto)",
            "elemento": "fuego",
            "resonancia_global": ["Isis", "Osiris"],
        },
        {
            "nombre_comun": "Cedro del Líbano",
            "nombre_cientifico": "Cedrus libani",
            "familia": "Pinaceae",
            "origen_geografico": "Líbano, Siria, Turquía",
            "descripcion_botanica": "Conífera de crecimiento lento y extrema longevidad (>2000 años). Madera incorruptible.",
            "significado_sagrado": "Árbol de los dioses en Mesopotamia. Gilgamesh destruyó el bosque de cedros. Salomón construyó el Templo con su madera.",
            "deidad_local": "Enlil/Anu (Mesopotamia), Baal (Fenicia)",
            "elemento": "fuego",
            "resonancia_global": ["Isis", "Hathor", "Enlil"],
        },
        {
            "nombre_comun": "Quillay",
            "nombre_cientifico": "Quillaja saponaria",
            "familia": "Quillajaceae",
            "origen_geografico": "Chile central — Santiago, Coquimbo, Biobío",
            "descripcion_botanica": "Árbol nativo chileno de zonas áridas y semisáridas. Corteza con saponinas — el jabón natural del bosque esclerófilo.",
            "significado_sagrado": "Árbol purificador del bosque esclerófilo. La corteza limpia — el fuego que no quema sino que purifica.",
            "deidad_local": "Pillán (Mapuche) — espíritu del fuego y los volcanes",
            "elemento": "fuego",
            "resonancia_global": ["Isis", "Pillán"],
            "nota_local": "Especie nativa de Santiago. Crece en cerros como San Cristóbal y La Dehesa.",
        },
        {
            "nombre_comun": "Palma Chilena",
            "nombre_cientifico": "Jubaea chilensis",
            "familia": "Arecaceae",
            "origen_geografico": "Chile central (endémica)",
            "descripcion_botanica": "La palma más austral del mundo. Tronco masivo (hasta 1.3m de diámetro). Vive 500-1000 años. En peligro de extinción.",
            "significado_sagrado": "Árbol solar por excelencia en el Chile central. Su miel (extraída matando el árbol) fue símbolo de sacrificio solar.",
            "deidad_local": "Ngünechen (Mapuche) — el dueño de la gente, aspectos solares",
            "elemento": "fuego",
            "resonancia_global": ["Isis", "Ra"],
            "nota_local": "Palmar del Ocoa (Parque Nacional La Campana) — el mayor bosque de palmas chilenas.",
        },
    ],

    # ── LILITH — Agua / Sur ──────────────────────────────────────────────────
    "lilith": [
        {
            "nombre_comun": "Fresno / Yggdrasil",
            "nombre_cientifico": "Fraxinus excelsior",
            "familia": "Oleaceae",
            "origen_geografico": "Europa, Cáucaso",
            "descripcion_botanica": "Árbol caducifolio de gran altura. Yemas negras características. Madera elástica y resistente.",
            "significado_sagrado": "Yggdrasil — el árbol cósmico nórdico que sostiene los nueve mundos. Sus raíces tocan Niflheim (hielo) y Muspelheim (fuego). Odín se colgó de él 9 días para obtener las runas.",
            "deidad_local": "Odín (Nórdico), Nornas (tejedoras del destino)",
            "elemento": "agua",
            "resonancia_global": ["Lilith", "Odín", "Hel"],
        },
        {
            "nombre_comun": "Sauce Llorón",
            "nombre_cientifico": "Salix babylonica",
            "familia": "Salicaceae",
            "origen_geografico": "China, naturalizado en todo el mundo a orillas de ríos",
            "descripcion_botanica": "Ramajes colgantes que tocan el agua. Raíces que buscan agresivamente la humedad. Primer árbol en brotar en primavera.",
            "significado_sagrado": "En Babilonia los israelitas colgaron sus arpas en los sauces y lloraron (Salmo 137). Árbol de duelo, memoria y lo que vive entre mundos.",
            "deidad_local": "Ishtar (Mesopotamia), Ereshkigal (mundo subterráneo)",
            "elemento": "agua",
            "resonancia_global": ["Lilith", "Ereshkigal", "Ishtar"],
        },
        {
            "nombre_comun": "Boldó",
            "nombre_cientifico": "Peumus boldus",
            "familia": "Monimiaceae",
            "origen_geografico": "Chile y Argentina — bosque esclerófilo",
            "descripcion_botanica": "Árbol dioico nativo chileno. Hojas aromáticas con alcaloides (boldina). Activo hepático y digestivo. Único miembro de su género.",
            "significado_sagrado": "Árbol de purificación hepática — el hígado filtra la sangre. Lilith como aquella que procesa lo tóxico, la sombra que depura.",
            "deidad_local": "Caicai Vilu (Mapuche) — serpiente del mar, fuerzas del agua oscura",
            "elemento": "agua",
            "resonancia_global": ["Lilith", "Ereshkigal"],
            "nota_local": "Especie nativa endémica. Cerros de Santiago, Valparaíso y zona costera.",
        },
        {
            "nombre_comun": "Arrayán",
            "nombre_cientifico": "Luma apiculata",
            "familia": "Myrtaceae",
            "origen_geografico": "Chile y Argentina — bosques valdivianos y ribereños",
            "descripcion_botanica": "Corteza canela brillante que se pela en láminas. Crece junto a ríos y lagos. Bosques de arrayán en Chiloé y Patagonia.",
            "significado_sagrado": "Árbol liminal — vive en la frontera entre el agua y la tierra. La corteza que se renueva constantemente habla de muerte y renacimiento.",
            "deidad_local": "Ngen ko (Mapuche) — dueño del agua",
            "elemento": "agua",
            "resonancia_global": ["Lilith", "Rusalka"],
            "nota_local": "Bosque de Arrayanes en la zona sur de Chile. Espectacular en otoño.",
        },
        {
            "nombre_comun": "Aliso negro / Alno",
            "nombre_cientifico": "Alnus glutinosa",
            "familia": "Betulaceae",
            "origen_geografico": "Europa, Norte de África, Asia occidental",
            "descripcion_botanica": "Árbol de ribera. Su madera sumergida en agua se vuelve más dura — no se pudre bajo el agua. Nódulos radicales que fijan nitrógeno.",
            "significado_sagrado": "Árbol celta del agua y la muerte. Bran el Bendito (mitología galesa) era el dios del Aliso. Su madera resiste la corrupción bajo el agua — símbolo de lo que sobrevive en las profundidades.",
            "deidad_local": "Bran (Galés), Cernunnos (Celta)",
            "elemento": "agua",
            "resonancia_global": ["Lilith", "Cernunnos", "Hel"],
        },
    ],

    # ── ARTEMISA — Tierra / Oeste ────────────────────────────────────────────
    "artemisa": [
        {
            "nombre_comun": "Ceiba / Yaxché",
            "nombre_cientifico": "Ceiba pentandra",
            "familia": "Malvaceae",
            "origen_geografico": "Mesoamérica y Caribe, África tropical (por dispersión)",
            "descripcion_botanica": "Uno de los árboles más grandes del neotrópico. Tronco con contrafuertes masivos. Sus fibras de kapok flotan — dispersión por agua y viento.",
            "significado_sagrado": "Yaxché — árbol de la vida maya. Conecta los nueve mundos del inframundo con los trece del cielo. En su tronco vive la Ceiba Verde del Centro.",
            "deidad_local": "Itzamná (Maya) — señor del árbol cósmico, Ix Chel — luna y tierra",
            "elemento": "tierra",
            "resonancia_global": ["Artemisa", "Itzamná"],
        },
        {
            "nombre_comun": "Tejo",
            "nombre_cientifico": "Taxus baccata",
            "familia": "Taxaceae",
            "origen_geografico": "Europa, Norte de África, Asia occidental",
            "descripcion_botanica": "Conífera de longevidad extrema (3000-5000 años documentados). Todo el árbol es venenoso excepto el arilo rojo. No tiene anillos de crecimiento regulares.",
            "significado_sagrado": "El árbol más longevo de Europa. Presente en cementerios desde antes del cristianismo — no como símbolo de muerte sino de inmortalidad. Los druidas lo usaban para sus rituales. Su veneno (taxina) se usaba en flechas.",
            "deidad_local": "Cernunnos (Celta), Hécate (Griega)",
            "elemento": "tierra",
            "resonancia_global": ["Artemisa", "Hécate", "Cernunnos"],
        },
        {
            "nombre_comun": "Roble",
            "nombre_cientifico": "Quercus robur",
            "familia": "Fagaceae",
            "origen_geografico": "Europa, desde la Península Ibérica hasta el Cáucaso",
            "descripcion_botanica": "El árbol más asociado al rayo en Europa por su madera altamente conductora. Longevo (800-1000 años). Ecosistema completo — 500+ especies dependen de él.",
            "significado_sagrado": "Árbol sagrado de Zeus/Júpiter (el rayo), Thor y los druidas. El oráculo de Dodona hablaba a través de los robles. El fuego del solsticio siempre era de roble.",
            "deidad_local": "Zeus (Grecia), Thor (Nórdico), Taranis (Celta)",
            "elemento": "tierra",
            "resonancia_global": ["Artemisa", "Zeus", "Thor", "Isis"],
            "nota_local": "El Roble Metropolitano en Santiago es Quercus robur introducido — árbol de parques y alamedas. Su fuego europeo resuena con Isis pero su arraigo en tierra chilena lo conecta con Artemisa y Ngünechen.",
        },
        {
            "nombre_comun": "Araucaria / Pehuén",
            "nombre_cientifico": "Araucaria araucana",
            "familia": "Araucariaceae",
            "origen_geografico": "Cordillera de los Andes y Nahuelbuta (Chile/Argentina)",
            "descripcion_botanica": "Árbol prehistórico sin cambios en 200 millones de años. Dioico. Longevidad de 1000-2000 años. El piñón (semilla) fue base alimentaria del pueblo Pehuenche.",
            "significado_sagrado": "Árbol sagrado del pueblo Pehuenche — su nombre significa 'gente del pehuén'. El árbol mismo es deidad: Pehuén Pillán. Su derecho a existir se reconoce en rituales de permiso (nguillatún) antes de cosechar.",
            "deidad_local": "Pehuén Pillán (Mapuche-Pehuenche) — el espíritu del árbol mismo",
            "elemento": "tierra",
            "resonancia_global": ["Artemisa", "Yaxché"],
            "nota_local": "Especie endémica protegida. Parque Nacional Conguillio, Nahuelbuta. En Santiago hay algunos ejemplares en parques.",
        },
        {
            "nombre_comun": "Peumo",
            "nombre_cientifico": "Cryptocarya peumus",
            "familia": "Lauraceae",
            "origen_geografico": "Chile central — endémica del bosque esclerófilo",
            "descripcion_botanica": "Árbol nativo de mediana altura. Hojas brillantes. Fruto rojo. Especie ancla del bosque esclerófilo chileno. Da nombre a múltiples lugares geográficos.",
            "significado_sagrado": "El árbol que da nombre al bosque esclerófilo del Chile central. Arraigado en la geografía local como pocos — Cerro Peumo, Quebrada Peumo, Villa Peumo. Es la tierra misma del Chile central.",
            "deidad_local": "Ngünechen (Mapuche) — dueño y creador de la tierra y la gente",
            "elemento": "tierra",
            "resonancia_global": ["Artemisa", "Ngünechen"],
            "nota_local": "Especie nativa de Santiago y zona central. Cerro San Cristóbal, quebradas de la precordillera.",
        },
    ],

    # ── AFRODITA — Aire / Este ───────────────────────────────────────────────
    "afrodita": [
        {
            "nombre_comun": "Mirto",
            "nombre_cientifico": "Myrtus communis",
            "familia": "Myrtaceae",
            "origen_geografico": "Mediterráneo, Oriente Próximo",
            "descripcion_botanica": "Arbusto aromático de hoja perenne. Flores blancas y bayas negras. El perfume de sus hojas al estrujarlas es inconfundible.",
            "significado_sagrado": "El árbol más sagrado de Afrodita. La diosa emergió del mar cubierta de mirto. En bodas romanas se usaban coronas de mirto. Símbolo del amor que perdura.",
            "deidad_local": "Afrodita/Venus (Greco-Romano)",
            "elemento": "aire",
            "resonancia_global": ["Afrodita", "Venus"],
        },
        {
            "nombre_comun": "Almendro",
            "nombre_cientifico": "Prunus dulcis",
            "familia": "Rosaceae",
            "origen_geografico": "Asia central (Irán, Uzbekistán), expandido por el Mediterráneo",
            "descripcion_botanica": "El primer árbol en florecer en el año — lo hace antes de tener hojas. Flores rosas y blancas en invierno tardío.",
            "significado_sagrado": "En la Biblia, el almendro es símbolo de vigilancia (Jeremías 1:11) porque 'despierta' antes que todos. En Grecia, Atis nació de una almendra. Primera promesa del aire primaveral.",
            "deidad_local": "Atis (Frigio), Cibeles (Anatolia)",
            "elemento": "aire",
            "resonancia_global": ["Afrodita", "Cibeles"],
        },
        {
            "nombre_comun": "Cerezo / Sakura",
            "nombre_cientifico": "Prunus serrulata",
            "familia": "Rosaceae",
            "origen_geografico": "Japón, China, Corea",
            "descripcion_botanica": "Floración espectacular de 1-2 semanas. Sin olor. Pétalos que caen con el viento.",
            "significado_sagrado": "Mono no aware — la belleza de lo impermanente. El sakura cayendo es la metáfora japonesa de la vida. Los samuráis identificaban su caída con el espíritu del guerrero.",
            "deidad_local": "Konohanasakuya-hime (Japonesa) — diosa de la flor del cerezo",
            "elemento": "aire",
            "resonancia_global": ["Afrodita", "Konohanasakuya"],
        },
        {
            "nombre_comun": "Litre",
            "nombre_cientifico": "Lithraea caustica",
            "familia": "Anacardiaceae",
            "origen_geografico": "Chile central — endémico",
            "descripcion_botanica": "Árbol nativo chileno. Savia urticante — produce dermatitis de contacto. Dioico. Muy resistente a la sequía. Florece en primavera con flores pequeñas y muy aromáticas.",
            "significado_sagrado": "La belleza que hiere. Afrodita tiene ese atributo — la atracción que lastima. El Litre es hermoso, aromático, pero tóxico al tacto. Eros y el peligro del amor.",
            "deidad_local": "Sin deidad Mapuche específica — es un árbol temido y respetado simultáneamente",
            "elemento": "aire",
            "resonancia_global": ["Afrodita", "Lilith"],
            "nota_local": "Especie nativa de Santiago y zona central. Quebradas y laderas secas.",
        },
        {
            "nombre_comun": "Jacarandá",
            "nombre_cientifico": "Jacaranda mimosifolia",
            "familia": "Bignoniaceae",
            "origen_geografico": "Bolivia, Argentina noroeste — naturalizado en Santiago y ciudades del mundo",
            "descripcion_botanica": "Flores azul-violeta espectaculares antes de que salgan las hojas. Alfombra violeta en el suelo.",
            "significado_sagrado": "Sin historia sagrada indígena propia — pero ha creado sincretismo urbano potente. En Buenos Aires y Santiago es el árbol del amor primaveral. La gente se fotografia bajo él, se declara, se besa.",
            "deidad_local": "Sin deidad formal — pero en Santiago se ha vuelto el árbol de Afrodita urbana por uso colectivo espontáneo",
            "elemento": "aire",
            "resonancia_global": ["Afrodita"],
            "nota_local": "Santiago tiene miles de jacarandás. Noviembre = la ciudad violeta.",
        },
    ],
}


# ───────────────────────────────────────────────────────────────────────────
#  DEIDADES LOCALES REGISTRADAS
#  Para el sistema de resonancia árbol ↔ deidad local ↔ deidades del altar
# ───────────────────────────────────────────────────────────────────────────

DEIDADES_LOCALES: dict[str, dict] = {
    "Ngünechen": {
        "tradicion": "Mapuche (Chile/Argentina)",
        "elemento": "tierra",
        "dominio": "creador de la gente, dueño de la vida y la muerte",
        "resonancia_altar": ["artemisa"],
    },
    "Pillán": {
        "tradicion": "Mapuche (Chile/Argentina)",
        "elemento": "fuego",
        "dominio": "volcanes, rayos, antepasados poderosos",
        "resonancia_altar": ["isis", "lilith"],
    },
    "Caicai Vilu": {
        "tradicion": "Mapuche (Chile/Argentina)",
        "elemento": "agua",
        "dominio": "serpiente del mar, inundaciones, fuerzas marinas caóticas",
        "resonancia_altar": ["lilith"],
    },
    "Tentén Vilu": {
        "tradicion": "Mapuche (Chile/Argentina)",
        "elemento": "tierra",
        "dominio": "serpiente de la tierra, protección, elevación del suelo ante el mar",
        "resonancia_altar": ["artemisa"],
    },
    "Pehuén Pillán": {
        "tradicion": "Mapuche-Pehuenche (Chile/Argentina)",
        "elemento": "tierra",
        "dominio": "espíritu del árbol araucaria, alimentación sagrada, longevidad",
        "resonancia_altar": ["artemisa"],
    },
    "Ngen ko": {
        "tradicion": "Mapuche",
        "elemento": "agua",
        "dominio": "dueño del agua, espíritu de ríos y vertientes",
        "resonancia_altar": ["lilith", "afrodita"],
    },
    "Itzamná": {
        "tradicion": "Maya (Mesoamérica)",
        "elemento": "tierra",
        "dominio": "señor del árbol cósmico, escritura, medicina, creación",
        "resonancia_altar": ["artemisa", "tutu"],
    },
    "Hathor": {
        "tradicion": "Egipcia",
        "elemento": "fuego",
        "dominio": "amor, belleza, música, cielo, árbol de la vida",
        "resonancia_altar": ["isis", "afrodita"],
    },
    "Konohanasakuya": {
        "tradicion": "Japonesa (Shinto)",
        "elemento": "aire",
        "dominio": "flor del cerezo, belleza efímera, primavera",
        "resonancia_altar": ["afrodita"],
    },
    "Cernunnos": {
        "tradicion": "Celta (Galia)",
        "elemento": "tierra",
        "dominio": "animales, bosques, fertilidad, mundo subterráneo",
        "resonancia_altar": ["artemisa", "lilith"],
    },
}
